repos:
  - repo: local
    hooks:
      # - id: make-test
      #   name: Run Make test
      #   entry: make run-tests-py
      #   language: system
      #   files: "^api/.*"   # only run if files under api/ changed
      #   stages: []

      - id: black
        name: Run Black on API
        entry: black
        language: system
        files: '^api/.*\.py$'

      # - id: lint
      #   name: Run pylint on API
      #   entry: make lint
      #   language: system
      #   files: "^api/.*"   # only run if files under api/ changed
