[tool.poetry]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
description = "Description"
authors = ["{{AUTHOR}}"]
readme = "README.md"
package-mode = false 

[tool.poetry.dependencies]
python = "^3.12,<3.14"
fastapi = {extras = ["standard"], version = "^0.116.1"}
uvicorn = "^0.35.0"
python-multipart = "^0.0.20"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
mypy = "^1.16.1"
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
internal = []